{
  "hash": "c1f6b1ae22be35efabe684b9c9a44953",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Measuring Adiposity\"\nsubtitle: \"BMI vs. DXA\"\ndescription: Compare BMI and DXA-based adiposity measures and use IPD corrections to improve regression inference under predicted outcomes.\nimage: images/adiposity_cover.png\nformat: html\n---\n\n\n\n\n\n## Background and Motivation\n\n### How Do We Measure Adiposity?\n\nBody mass index (BMI) is the most commonly used anthropometric proxy for \nadiposity in epidemiologic studies and clinical settings. It is simple to \ncalculate, weight in kilograms divided by height in meters squared, and has \nwell-established cut-points for classifying patients as overweight or obese. \nHowever, BMI does not distinguish between fat mass and lean mass, nor does it \ncapture fat distribution (visceral versus subcutaneous). As a result, BMI can \nboth under- and over-estimate true adiposity in key subgroups. For example \nmuscular individuals (e.g., athletes) may be misclassified as \"obese,\" while \nolder adults with sarcopenia (low muscle mass) may fall below BMI thresholds \ndespite having high percent body fat. \n\n<br>\n\n![*Source: https://www.medrxiv.org/content/10.1101/2025.04.01.25325037v1.full.pdf*](images/bmi_flowchart.png){width=100%}\n\n<br>\n\nWaist circumference (WC) is another simple measure of central adiposity that \nmay better reflect visceral fat, a key driver of metabolic risk. Standard WC \ncut-points (e.g., ≥ 102 cm in men, ≥ 88 cm in women) identify individuals at \nincreased cardiometabolic risk, even when their BMI is in the normal or \noverweight range. Yet WC also does not directly quantify total body fat and \nis influenced by body build, posture, and measurement error.\n\nDual-energy X-ray absorptiometry (DXA) provides a more accurate \"gold-standard\" \nmeasure of body composition by directly quantifying total and regional fat and \nlean mass. DXA-derived percent fat thresholds (e.g., > 30% in men, > 42% in \nwomen) have been validated against metabolic outcomes. Comparing BMI-based \nobesity (BMI ≥ 30 kg/m²) and WC-based obesity (WC ≥ 102 cm men, ≥ 88 cm women) \nwith DXA-defined obesity reveals where and how often these common \nanthropometric proxies misclassify true adiposity.\n\nIt is worth noting that BMI is often defended as a valid measure for \npopulation-level inference, under the assumption that individual-level \nmisclassification errors are harmless when estimating group-level trends. \nThis justification appears frequently in epidemiology, where BMI is treated \nas a convenient stand-in for adiposity in regression models. But this reasoning \nmasks a deeper issue central to the IPD framework: BMI is itself a prediction \nmodel, a crude one, but a model nonetheless. It encodes a deterministic \nfunction (weight divided by height squared) to approximate an unobserved \nlatent quantity (body fat), and like any prediction model, it introduces \nsystematic biases that may not vanish with aggregation. IPD adopts a \nprediction-agnostic perspective: whether the surrogate is a simple index like \nBMI or a high-dimensional neural network, the challenge is the same: how to \ndraw valid statistical inference when the outcome is a model-based proxy. By \ntreating BMI as a prediction rather than a ground truth, we clarify the role \nof uncertainty, calibration, and correction, and demonstrate how IPD methods \ncan help recover valid estimates even when only such surrogates are available.\n\nIn this module, we will use data from the [National Health and Nutrition Examination Survey  (NHANES)](https://www.cdc.gov/nchs/nhanes/index.html) to:\n\n1. **Load** BMI, WC, and DXA-based measures of adiposity and their associated \nfeatures\n2. **Define** obesity by three standards:\n    - BMI (≥ 30 kg/m²)\n    - Waist circumference (men ≥ 102 cm; women ≥ 88 cm)\n    - DXA % body fat (> 30% men; > 42% women)\n3.  **Visualize** misclassification rates overall and by age, sex, and \nrace/ethnicity\n4.  **Calibrate** both BMI and WC-based obesity measures to DXA using the \n`ipd` package\n5.  **Discuss** implications for research and practice\n\nBy the end, we may have a better understanding of the strengths and limitations \nof BMI and WC as proxies for adiposity, know how to assess \ntheir sensitivity and specificity versus DXA, and be equipped to correct for \nmeasurement error using IPD when only BMI/WC are available.\n\n### NHANES\n\nThe National Health and Nutrition Examination Survey \n([NHANES](https://www.cdc.gov/nchs/nhanes/index.html)) is a nationally \nrepresentative program conducted by the U.S. Centers for Disease Control \nand Prevention that combines in-home interviews with standardized physical \nexaminations and laboratory tests to assess the health and nutritional \nstatus of Americans. Initiated in the early 1960s and carried out continuously \nsince 1999 in two-year cycles, NHANES informs public health policy, tracks \ntrends in chronic conditions and risk factors, and support research on diet, \ndisease, and health disparities. NHANES provides:\n\n- **DXA-measured percent body fat** (`DXDTOPF`) for a subset of participants\n- **BMI** (`BMXBMI`), derived from measured height and weight\n- **Waist circumference** (`BMXWAIST`), a potential measure of central fat\n\nAs DXA scans are costly and time-consuming, many studies only record BMI and \nWC. When our scientific question involves true adiposity (e.g., its association \nwith certain risk factors), but we only have BMI and WC in most participants, \nwe can use `ipd` to correct our downstream inference on % body fat to account \nfor the fact that these proxies are being used in place of the true DXA \nmeasurement.\n\n**Note:** DXA scans were collected through the **2017 - 2018** NHANES cycle \nbut were suspended during the COVID-19 pandemic. As a result, subsequent \nwaves, including the **August 2021 - August 2023** data, do **not** include \nDXA measurements. In this tutorial, we will therefore:\n\n1. Use the **2017-2018** wave as our *labeled* data (which includes `DXDTOPF`).  \n2. Use **IPD** to correct our inference when estimating associations between \n% body fat and other covariates in the absence of direct DXA measurements in \nthe *unlabeled* **August 2021 - August 2023** wave. \n\nThis approach lets us leverage historic DXA data to predict adiposity in more \nrecent participants, enabling unbiased inference across pre- and post-pandemic \ncohorts.\n\n## Data Preparation and Exploration\n\nWe will now load a pre-compiled NHANES dataset, explore key variables (BMI, \nwaist circumference, DXA % body fat) by cohort, and define obesity categories \nfor later misclassification analyses and IPD.\n\n### Loading the Pre-Compiled NHANES Data\n\nFor convenience, we prepared and saved a data file, `data/NHANES.rda`, which\ncontains a tibble, **NHANES**, with the following columns:\n\n- `SEQN`      - Respondent ID  \n- `Cohort`    - Factor: \"2017-2018\" or \"2021-2023\"  \n- `Age`       - Factor: \"Under 20\", \"20-39\", \"40-59\", or \"60+\" \n- `Sex`       - Factor: \"Male\" or \"Female\"  \n- `Race`      - Factor: \"Non-Hispanic White\", \"Hispanic\", \"Non-Hispanic Black\", \"Non-Hispanic Asian\", or \"Other Race - Including Multi-Racial\" \n- `Smoking`   - Factor: \"Never Smoker\", \"Former Smoker\", or \"Current Smoker\"\n- `Education` - Factor: \"Less than high school\", \"High school graduate/GED or equivalent\", \"Some college or AA degree\", \"College graduate or above\", or \"Refused/Unknown\" \n- `BMXBMI`    - Body Mass Index (kg/m²)  \n- `BMXWAIST`  - Waist Circumference (cm)  \n- `DXDTOPF`   - DXA Percent Body Fat (only measured in 2017-2018; `NA` in 2021-2023)\n- `WTMEC4YR`  - Four-Year Adjusted Survey Weights\n\n**Note:** The the code used to produce this dataset is available in this \nrepository at `inst/NHANES_DATA.R`.\n\n### Install and Load the Necessary Packages\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Install these packages if you have not already:\n# install.packages(c(\"ipd\", \"broom\", \"scales\", \"tidyverse\"))\n\nlibrary(ipd)        # Inference with predicted data\nlibrary(broom)      # Convert model objects (lm, glm, ipd) into tidy data.frames\nlibrary(scales)     # Formatting scales and labels for ggplot2\nlibrary(tidyverse)  # Meta‐package for data manipulation and visualization\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.0     ✔ readr     2.1.6\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.2     ✔ tibble    3.3.1\n✔ lubridate 1.9.5     ✔ tidyr     1.3.2\n✔ purrr     1.2.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ readr::col_factor() masks scales::col_factor()\n✖ purrr::discard()    masks scales::discard()\n✖ dplyr::filter()     masks stats::filter()\n✖ dplyr::lag()        masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\n\n\n\n### Load the Data\n\nWe first load the prepared dataset and take a look at its features:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the dataset\nload(\"data/NHANES.RData\")\n\n# Inspect its structure\nglimpse(NHANES)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 11,782\nColumns: 11\n$ SEQN      <dbl> 93706, 93707, 93711, 93712, 93714, 93717, 93719, 93725, 9372…\n$ Cohort    <fct> 2017-2018, 2017-2018, 2017-2018, 2017-2018, 2017-2018, 2017-…\n$ Age       <fct> Under 20, Under 20, 40-59, Under 20, 40-59, 20-39, Under 20,…\n$ Sex       <fct> Male, Male, Male, Male, Female, Male, Female, Female, Male, …\n$ Race      <fct> Non-Hispanic Asian, Other Race - Including Multi-Racial, Non…\n$ Smoking   <fct> NA, NA, NA, NA, Former Smoker, NA, NA, NA, NA, NA, NA, NA, N…\n$ Education <fct> Refused/Unknown, Refused/Unknown, College graduate or above,…\n$ BMXBMI    <dbl> 21.5, 18.1, 21.3, 19.7, 39.9, 24.5, 26.0, 16.1, 27.6, 28.6, …\n$ BMXWAIST  <dbl> 79.3, 64.1, 86.6, 72.0, 118.4, 86.2, 86.0, 66.8, 101.5, 96.3…\n$ DXDTOPF   <dbl> 22.7, 19.0, 22.8, 16.7, 42.1, 20.4, 33.4, 26.9, 29.4, 22.8, …\n$ WTMEC4YR  <dbl> 4361.720, 3532.305, 6195.460, 15168.327, 7739.791, 30058.968…\n```\n\n\n:::\n:::\n\n\n\n\n\n### Overview by Cohort\n\nWe can now get a sense of the different cohorts and our variables of interest:\n\n#### Sample Sizes\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  count(Cohort) |>\n  mutate(pct = n / sum(n) * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Cohort    n      pct\n1 2017-2018 3617 30.69937\n2 2021-2023 8165 69.30063\n```\n\n\n:::\n:::\n\n\n\n\n\n#### DXA Missingness\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  group_by(Cohort) |>\n  summarize(\n    total       = n(),\n    pct_missing = mean(is.na(DXDTOPF)) * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  Cohort    total pct_missing\n  <fct>     <int>       <dbl>\n1 2017-2018  3617           0\n2 2021-2023  8165         100\n```\n\n\n:::\n:::\n\n\n\n\n\n> **Expected:**\n>\n> * 2017-2018: 100% of DXA (`DXDTOPF`) present (using those with mobile examination center (MEC) tests and MEC weights).\n> * 2021-2023: 100% missing for `DXDTOPF` (no DXA data post-pandemic).\n\n### Descriptive Statistics\n\n#### BMI, Waist Circumference, and DXA % Fat\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  group_by(Cohort) |>\n  summarize(\n    BMI_mean = mean(BMXBMI),\n    BMI_sd   = sd(BMXBMI),\n    WC_mean  = mean(BMXWAIST),\n    WC_sd    = sd(BMXWAIST),\n    DXA_mean = mean(DXDTOPF),\n    DXA_sd   = sd(DXDTOPF)\n  ) |>\n  pivot_longer(-Cohort)|>\n  separate(name, c(\"Metric\", \"Statistic\")) |>\n  pivot_wider(names_from = Statistic, values_from = value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  Cohort    Metric  mean    sd\n  <fct>     <chr>  <dbl> <dbl>\n1 2017-2018 BMI     26.5  7.24\n2 2017-2018 WC      89.3 18.8 \n3 2017-2018 DXA     32.3  8.70\n4 2021-2023 BMI     27.1  7.96\n5 2021-2023 WC      92.1 22.0 \n6 2021-2023 DXA     NA   NA   \n```\n\n\n:::\n:::\n\n\n\n\n\n#### Distributions of Continuous Measures of Adiposity\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  pivot_longer(c(BMXBMI, BMXWAIST, DXDTOPF)) |>\n  ggplot(aes(x = value, fill = Cohort)) +\n    facet_wrap(~ name, scales = \"free\") +\n    geom_histogram(alpha = 0.6, position = \"identity\", bins = 30) +\n    scale_fill_manual(values = c(\"#00C1D5\", \"#AA4AC4\")) +\n    labs(\n      title = \"Measures of Adiposity by Cohort\", \n      x = \"BMI (kg/m2), WC (cm), or % Fat\", \n      y = \"Count\") +\n    theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 8165 rows containing non-finite outside the scale range\n(`stat_bin()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Unit02_MeasuringAdiposity_files/figure-html/unnamed-chunk-6-1.png){width=100%}\n:::\n:::\n\n\n\n\n\n#### DXA vs Anthropometry in 2017-2018\n\nOnly the 2017-2018 cohort has `DXDTOPF`, so we examine how BMI and WC relate to true % body fat among the study participants in this wave:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES |>\n  filter(Cohort == \"2017-2018\") |>\n  pivot_longer(c(BMXBMI, BMXWAIST)) |>\n  ggplot(aes(x = value, y = DXDTOPF)) +\n    facet_wrap(~ name, scales = \"free_x\") +\n    geom_point(alpha = 0.4) +\n    geom_smooth(method = \"lm\", color = \"#1B365D\") +\n    labs(\n      title = \"DXA % Body Fat vs BMI and WC (2017-2018)\",\n      x = \"BMI (kg/m2) or WC (cm)\", y = \"DXDTOPF (%)\") +\n    theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Unit02_MeasuringAdiposity_files/figure-html/unnamed-chunk-7-1.png){width=100%}\n:::\n:::\n\n\n\n\n\nLet's also compare these measures by Sex. We can also add reference lines to \nsee where the measure-specific obesity cut-offs would be:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncutoffs <- tibble(\n  name = c(\"BMXBMI\", \"BMXBMI\", \"BMXWAIST\", \"BMXWAIST\"),\n  Sex  = c(\"Male\", \"Female\", \"Male\", \"Female\"),\n  xint = c(30, 30, 102, 88),\n  yint = c(30, 42,  30, 42)\n)\n\nNHANES |>\n  filter(Cohort == \"2017-2018\") |>\n  pivot_longer(c(BMXBMI, BMXWAIST)) |>\n  ggplot(aes(x = value, y = DXDTOPF, group = Sex, fill = Sex, color = Sex)) +\n    facet_wrap(~ name, scales = \"free_x\") +\n    geom_point(alpha = 0.4) +\n    geom_smooth(method = \"lm\") +\n    geom_vline(data = cutoffs, \n      aes(xintercept = xint, color = Sex), linetype = \"dashed\") +\n    geom_hline(data = cutoffs, \n      aes(yintercept = yint, color = Sex), linetype = \"dashed\") +\n    scale_fill_manual(values = c(\"#00C1D5\", \"#AA4AC4\")) +\n    scale_color_manual(values = c(\"#00C1D5\", \"#AA4AC4\")) +\n    labs(\n      title = \"DXA % Body Fat vs BMI and WC (2017-2018)\",\n      x = \"BMI (kg/m2) or WC (cm)\", y = \"DXDTOPF (%)\") +\n    theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Unit02_MeasuringAdiposity_files/figure-html/unnamed-chunk-8-1.png){width=100%}\n:::\n:::\n\n\n\n\n\n> **Interpretation:**\n> \n> * There is a strong *positive linear relationship* between both BMI and WC with DXA body fat percentage.\n> * This relationship is apparent across both sexes, but slopes differ, indicating *different body composition patterns* between males and females.\n> * The presence of individuals in *mismatched quadrants* (e.g., high BMI but low body fat) suggests limitations in using BMI/WC alone as diagnostic tools, particularly across sexes.\n>\n\n## Defining Obesity Categories\n\nLet us create three binary indicators:\n\n* **`obese_BMI`**: BMI ≥ 30 kg/m²\n* **`obese_WC`**: WC ≥ 102 cm (men) or ≥ 88 cm (women)\n* **`obese_DXA`**: DXA % Fat > 30% (men) or > 42% (women)\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNHANES <- NHANES |>\n  mutate(\n    obese_BMI = BMXBMI >= 30,\n    obese_WC  = case_when(\n      Sex == \"Male\"   & BMXWAIST >= 102 ~ TRUE,\n      Sex == \"Female\" & BMXWAIST >=  88 ~ TRUE,\n      .default                          = FALSE),\n    obese_DXA = case_when(\n      is.na(DXDTOPF)                 ~ NA,\n      Sex == \"Male\"   & DXDTOPF > 30 ~ TRUE,\n      Sex == \"Female\" & DXDTOPF > 42 ~ TRUE,\n      .default                       = FALSE)\n  )\n```\n:::\n\n\n\n\n\n### Misclassification in 2017-2018\n\nCompare BMI-defined vs DXA-defined obesity:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Overall\nNHANES |>\n  filter(Cohort == \"2017-2018\") |>\n  count(obese_DXA, obese_BMI) |>\n  mutate(percent = sprintf(\"%.1f%%\", 100 * n / sum(n)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  obese_DXA obese_BMI    n percent\n1     FALSE     FALSE 2180   60.3%\n2     FALSE      TRUE  307    8.5%\n3      TRUE     FALSE  415   11.5%\n4      TRUE      TRUE  715   19.8%\n```\n\n\n:::\n\n```{.r .cell-code}\n# By Sex\nNHANES |>\n  filter(Cohort == \"2017-2018\") |>\n  count(Sex, obese_DXA, obese_BMI) |>\n  group_by(Sex) |>\n  mutate(percent = sprintf(\"%.1f%%\", 100 * n / sum(n))) |>\n  ungroup()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 5\n  Sex    obese_DXA obese_BMI     n percent\n  <fct>  <lgl>     <lgl>     <int> <chr>  \n1 Male   FALSE     FALSE      1003 56.1%  \n2 Male   FALSE     TRUE        138 7.7%   \n3 Male   TRUE      FALSE       302 16.9%  \n4 Male   TRUE      TRUE        345 19.3%  \n5 Female FALSE     FALSE      1177 64.4%  \n6 Female FALSE     TRUE        169 9.2%   \n7 Female TRUE      FALSE       113 6.2%   \n8 Female TRUE      TRUE        370 20.2%  \n```\n\n\n:::\n:::\n\n\n\n\n\nAnd WC-defined vs DXA-defined:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Overall\nNHANES |>\n  filter(Cohort == \"2017-2018\") |>\n  count(obese_DXA, obese_WC) |>\n  mutate(percent = sprintf(\"%.1f%%\", 100 * n / sum(n)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  obese_DXA obese_WC    n percent\n1     FALSE    FALSE 1959   54.2%\n2     FALSE     TRUE  528   14.6%\n3      TRUE    FALSE  319    8.8%\n4      TRUE     TRUE  811   22.4%\n```\n\n\n:::\n\n```{.r .cell-code}\n# By Sex\nNHANES |>\n  filter(Cohort == \"2017-2018\") |>\n  count(Sex, obese_DXA, obese_WC) |>\n  group_by(Sex) |>\n  mutate(percent = sprintf(\"%.1f%%\", 100 * n / sum(n))) |>\n  ungroup()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 5\n  Sex    obese_DXA obese_WC     n percent\n  <fct>  <lgl>     <lgl>    <int> <chr>  \n1 Male   FALSE     FALSE     1020 57.0%  \n2 Male   FALSE     TRUE       121 6.8%   \n3 Male   TRUE      FALSE      286 16.0%  \n4 Male   TRUE      TRUE       361 20.2%  \n5 Female FALSE     FALSE      939 51.3%  \n6 Female FALSE     TRUE       407 22.3%  \n7 Female TRUE      FALSE       33 1.8%   \n8 Female TRUE      TRUE       450 24.6%  \n```\n\n\n:::\n:::\n\n\n\n\n\n> **Interpretation:**\n> \n> *BMI vs. DXA:*\n>\n> * The misclassification rate is 8.5% + 11.5% = 20.0%, with BMI underestimating DXA-defined obesity more than it overestimates it.\n> * By sex, BMI misses many obese males per DXA, indicating underestimation of adiposity, but it overcalls obesity more often than it misses it in females.\n> * BMI is less sensitive for men, while women are more likely to be labeled obese by BMI even when not by DXA, indicating reduced specificity.\n>\n> *WC vs. DXA:*\n>\n> * The misclassification rate is 14.6% + 8.8% = 23.4%, with WC slightly overestimating obesity more than it underestimates, opposite to BMI.\n> * WC underestimates DXA-defined obesity in males, similar to BMI, but overestimates obesity in females, often classifying non-obese women as obese.\n> * For women, WC has higher sensitivity but lower specificity than BMI, as it detects more DXA-obese individuals but also overcalls many who are not.\n\n### Additional Stratified Comparisons: Grouped Bar Charts by Measure\n\nLet us reshape the data to long format so that BMI, WC, and DXA-defined obesity \nare all in one \"Measure\" column:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Assume NHANES is already loaded and has Cohort, Age, Sex, Race, \n# and the three obesity variables\nnhanes_long <- NHANES |>\n  select(Cohort, Age, Sex, Race, obese_BMI, obese_WC, obese_DXA) |>\n  pivot_longer(\n    cols = starts_with(\"obese_\"),\n    names_to = \"Measure\",\n    values_to = \"Obese\"\n  ) |>\n  mutate(\n    Measure = recode(Measure,\n      obese_BMI = \"BMI\",\n      obese_WC  = \"Waist Circumference\",\n      obese_DXA = \"DXA\"\n    )\n  ) |>\n  filter(!is.na(Obese))\n```\n:::\n\n\n\n\n\n#### By Age Group\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop_age <- nhanes_long |>\n  group_by(Cohort, Age, Measure, Obese) |>\n  summarize(n = n(), .groups = \"drop\") |>\n  group_by(Cohort, Age, Measure) |>\n  mutate(prop = n / sum(n))\n\nggplot(prop_age, aes(x = Age, y = prop, fill = Obese)) +\n  geom_col(position = \"stack\") +\n  facet_grid(Cohort ~ Measure) +\n  scale_y_continuous(labels = percent_format(accuracy = 1)) +\n  scale_fill_manual(values = c(\"#00C1D5\", \"#AA4AC4\")) +\n  scale_color_manual(values = c(\"#00C1D5\", \"#AA4AC4\")) +\n  labs(\n    x     = \"Age Group\",\n    y     = \"Percent\",\n    fill  = \"Obesity Status\",\n    title = \"Obesity Classification by Age, Cohort, and Measure\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in min(x): no non-missing arguments to min; returning Inf\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in max(x): no non-missing arguments to max; returning -Inf\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Unit02_MeasuringAdiposity_files/figure-html/unnamed-chunk-13-1.png){width=100%}\n:::\n:::\n\n\n\n\n\n#### By Sex\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop_sex <- nhanes_long |>\n  group_by(Cohort, Sex, Measure, Obese) |>\n  summarize(n = n(), .groups = \"drop\") |>\n  group_by(Cohort, Sex, Measure) |>\n  mutate(prop = n / sum(n))\n\nggplot(prop_sex, aes(x = Sex, y = prop, fill = Obese)) +\n  geom_col(position = \"stack\") +\n  facet_grid(Cohort ~ Measure) +\n  scale_y_continuous(labels = percent_format(accuracy = 1)) +\n  scale_fill_manual(values = c(\"#00C1D5\", \"#AA4AC4\")) +\n  scale_color_manual(values = c(\"#00C1D5\", \"#AA4AC4\")) +\n  labs(\n    x     = \"Sex\",\n    y     = \"Percent\",\n    fill  = \"Obesity Status\",\n    title = \"Obesity Classification by Sex, Cohort, and Measure\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in min(x): no non-missing arguments to min; returning Inf\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in max(x): no non-missing arguments to max; returning -Inf\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Unit02_MeasuringAdiposity_files/figure-html/unnamed-chunk-14-1.png){width=100%}\n:::\n:::\n\n\n\n\n\n#### By Race/Ethnicity\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop_race <- nhanes_long |>\n  group_by(Cohort, Race, Measure, Obese) |>\n  summarize(n = n(), .groups = \"drop\") |>\n  group_by(Cohort, Race, Measure) |>\n  mutate(prop = n / sum(n))\n\nggplot(prop_race, aes(x = Race, y = prop, fill = Obese)) +\n  geom_col(position = \"stack\") +\n  facet_grid(Cohort ~ Measure) +\n  scale_y_continuous(labels = percent_format(accuracy = 1)) +\n  scale_fill_manual(values = c(\"#00C1D5\", \"#AA4AC4\")) +\n  scale_color_manual(values = c(\"#00C1D5\", \"#AA4AC4\")) +\n  labs(\n    x     = \"Race / Ethnicity\",\n    y     = \"Percent\",\n    fill  = \"Obesity Status\",\n    title = \"Obesity Classification by Race/Ethnicity, Cohort, and Measure\"\n  ) +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in min(x): no non-missing arguments to min; returning Inf\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in max(x): no non-missing arguments to max; returning -Inf\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Unit02_MeasuringAdiposity_files/figure-html/unnamed-chunk-15-1.png){width=100%}\n:::\n:::\n\n\n\n\n\n### Discussion\n\nBMI misclassification varies systematically across subgroups:\n\n-   **Age**: Young adults (18-34) often have lower lean mass, so normal-BMI individuals can still have high body fat (\"normal-weight obesity\").\n-   **Sex**: Women generally have higher percent-fat at the same BMI; sex-specific DXA thresholds help adjust for this.\n-   **Race/Ethnicity**: Differences in body composition and fat distribution mean that a single BMI cut-point may not correspond to the same adiposity level across groups.\n\n**Implications**: Reliance on BMI alone can bias epidemiologic associations with true adiposity-driven outcomes (e.g., diabetes, cardiovascular disease). When DXA or other body-composition measures are impractical, consider calibration equations or subgroup-specific BMI thresholds.\n\n**Next:** we will split the combined NHANES data into **labeled** (2017-2018 with `DXDTOPF`) and **unlabeled** (2021-2023 without DXA), and then proceed with IPD using BMI or WC as our proxy.\n\n## Demographic Associations: Naive vs Classical vs IPD\n\n### Naive vs Classical vs IPD Inference\n\nWe are interested in studying the *association* between *true percent body fat* \n(DXA % fat) and risk factors such as age, sex, and race. We model the *binary*\nobesity outcome (DXA-defined \"true\" vs BMI/WC \"proxy\") as a function of *Age*, \n*Sex*, and *Race* using logistic regression:\n\n- **Naive:** proxy-only model on *unlabeled* data (2021-2023)  \n- **Classical:** true-only model on *labeled* data (2017-2018)  \n- **IPD:** combine both while correcting for proxy error\n\n#### Setup Labeled vs Unlabeled Data\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Split NHANES into labeled (DXA available) vs unlabeled\nlabeled   <- NHANES |> filter(Cohort == \"2017-2018\")\nunlabeled <- NHANES |> filter(Cohort == \"2021-2023\")\n\n# Stack for IPD\ncombined <- bind_rows(\n  labeled   |> mutate(set_label = \"labeled\"),\n  unlabeled |> mutate(set_label = \"unlabeled\")\n)\n```\n:::\n\n\n\n\n\n#### Naive versus Classical Regressions\n\nWe fit:\n\n* **Naive-BMI:**   `lm(BMI ~ Age + Sex + Race,   data = unlabeled)`\n* **Naive-WC:**    `lm(WC  ~ Age + Sex + Race,   data = unlabeled)`\n* **Classical:**   `lm(DXDTOPF ~ Age + Sex + Race, data = labeled)`\n\nFor the naive method, we treat BMI- and WC-based obesity (our 'predictions) as \nthe true outcomes, fit on the **unlabeled** participants:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Naive on unlabeled using BMI\nnaive_bmi_fit <- glm(obese_BMI ~ Age + Sex + Race, \n  family = binomial, data = unlabeled)\nnaive_bmi_df  <- broom::tidy(naive_bmi_fit) |>\n  mutate(method = \"Naive (BMI)\")\n\n# Naive on unlabeled using WC\nnaive_wc_fit <- glm(obese_WC ~ Age + Sex + Race,\n  family = binomial, data = unlabeled)\nnaive_wc_df  <- broom::tidy(naive_wc_fit) |>\n  mutate(method = \"Naive (WC)\")\n```\n:::\n\n\n\n\n\n> **Interpretation:**\n>\n> -   Because we 'predicted' obesity using BMI or WC, the \"naive\" coefficient are biased and the confidence intervals are artifically too narrow.\n\nFor the classical approach, we fit the true model on the **labeled** subset (with actual DXA % fat). That is:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Classical on labeled using DXA\nclass_fit <- glm(obese_DXA ~ Age + Sex + Race,\n  family = binomial, data = labeled)\nclass_df  <- broom::tidy(class_fit) |>\n  mutate(method = \"Classical (DXA)\")\n\n# Combine\ncoef_df <- bind_rows(naive_bmi_df, naive_wc_df, class_df) |>\n  filter(term != \"(Intercept)\") |>\n  mutate(\n    term = recode(term,\n      \"Age20-39\" = \"Age 20-39 (vs Under 20)\",\n      \"Age40-59\" = \"Age 40-59 (vs Under 20)\",\n      \"Age60+\"   = \"Age 60+ (vs Under 20)\",\n      \"SexFemale\" = \"Female (vs Male)\",\n      \"RaceNon-Hispanic Black\" = \"Non-Hispanic Black (vs Non-Hispanic White)\",\n      \"RaceNon-Hispanic Asian\" = \"Non-Hispanic Asian (vs Non-Hispanic White)\",\n      \"RaceHispanic\" = \"Hispanic (vs Non-Hispanic White)\",\n      \"RaceOther Race - Including Multi-Racial\" = \"Other Race - Including Multi-Racial (vs Non-Hispanic White)\"\n    ),\n    method = factor(method, levels = c(\"Classical (DXA)\", \"Naive (BMI)\", \"Naive (WC)\"))\n  )\n    \n# Forest plot\nggplot(coef_df, aes(x = estimate, y = term, color = method)) +\n  geom_point(position = position_dodge(width = 0.6)) +\n  geom_errorbarh(aes(xmin = estimate - 1.96 * std.error,\n                     xmax = estimate + 1.96 * std.error),\n                 height = 0.2,\n                 position = position_dodge(width = 0.6)) +\n  geom_vline(xintercept = 0, linetype = \"dashed\") +\n  scale_y_discrete(limits = rev) +\n  scale_fill_manual(values  = c(\"#1B365D\", \"#00C1D5\", \"#AA4AC4\")) +\n  scale_color_manual(values = c(\"#1B365D\", \"#00C1D5\", \"#AA4AC4\")) +\n  labs(\n    x = \"Log-Odds Estimate (95% CI)\",\n    y = \"Covariate\",\n    title = \"Comparison of Obesity Model Coefficients\",\n    color = \"Model Type\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: `geom_errorbarh()` was deprecated in ggplot2 4.0.0.\nℹ Please use the `orientation` argument of `geom_errorbar()` instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`height` was translated to `width`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Unit02_MeasuringAdiposity_files/figure-html/unnamed-chunk-18-1.png){width=100%}\n:::\n:::\n\n\n\n\n\n> **How to interpret these results?**\n>\n> * Notice the differences in significance and magnitude, even direction/sign change depending on the measure of obesity used!\n>\n> * *Age Groups (vs Under 20):* All age groups have positive coefficients, indicating higher odds of DXA-defined obesity with age, but naive BMI and WC show even larger positive estimates, suggesting that BMI and WC may over-classify obesity in older adults compared to DXA.\n>\n> * *Sex (Female vs Male):* DXA shows a negative association, while BMI and WC have uch larger effect sizes, particularly for WC, implying that WC-based obesity strongly overclassifies women as obese relative to DXA.\n>\n> * *Race/Ethnicity (vs Non-Hispanic White):* BMI/WC models show larger effects in Non-Hispanic Black participants, again hinting that BMI and WC may overestimate obesity in this group, while the opposite is true for Non-Hispanic Asian participants.\n\n#### IPD Corrections\n\nWe now apply **IPD** to leverage all participants (labeled + unlabeled) while adjusting for prediction error. We run two IPD analyses, one using `BMI` as our '`f`' and one using `WC`.\n\n> **A note on two calling styles:**\n>\n> We can either provide a single, *combined* dataset to the `data` argument and the name of the column that gives the set labels in `label`:\n>\n> ipd_bmi_1 <- ipd(\n>   formula = obese_DXA - obese_BMI ~ Age + Sex + Race,\n>   data    = combined,\n>   label   = \"set_label\",\n>   model   = \"logistic\",\n>   method  = \"pspa\"\n> )\n>\n> **or** we can provide the *labeled* set to `data` and the *unlabeled* set to `unlabeled_data` separately:\n>\n> ipd_bmi_2 <- ipd(\n>   formula        = obese_DXA - obese_BMI ~ Age + Sex + Race,\n>   data           = labeled,\n>   unlabeled_data = unlabeled,\n>   model          = \"logistic\",\n>   method         = \"pspa\"\n> )\n\nNow we can try to run the IPD model:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Note: This code chunk results in an error, but we have an informative warning\n# We can try running it and see!\n\n# ipd_bmi_fit <- ipd(\n#     formula = obese_DXA - obese_BMI ~ Age + Sex + Race,\n#     method  = \"pspa\",\n#     model   = \"logistic\",\n#     data    = combined,\n#     label   = \"set_label\"\n# )\n# \n# ipd_wc_fit <- ipd(\n#     formula = obese_DXA - obese_WC ~ Age + Sex + Race,\n#     method  = \"pspa\",\n#     model   = \"logistic\",\n#     data    = labeled,\n#     unlabeled_data = unlabeled\n# )\n```\n:::\n\n\n\n\n\n> **We get an informative warning:**\n>\n> Warning in .warn_differing_levels(inp\\$data_l, inp\\$data_u, factor_vars):\n> Differing factor levels between labeled and unlabeled data:\n>\n> Warning:  - Age:\n>     labeled = [Under 20, 20-39, 40-59]\n>     unlabeled = [Under 20, 20-39, 40-59, 60+]\n>\n\nWe can see that the *labeled* subset does *not* include any `\"60+\"` observations, but IPD expects the same factor levels in both sets in order to fit the model using all the data. To fix this, let us refactor both the *labeled* and *unlabeled* data so they have consistent age categories:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Recode age\nNHANES2 <- NHANES |>\n  mutate(Age_recode = fct_collapse(Age, `40+` = c(\"40-59\", \"60+\")))\n      \n# Split NHANES into labeled (DXA available) vs unlabeled\nlabeled2   <- NHANES2 |> \n  filter(Cohort == \"2017-2018\") |> \n  select(obese_DXA, obese_BMI, obese_WC, Age_recode, Sex, Race)\nunlabeled2 <- NHANES2 |> filter(Cohort == \"2021-2023\") |> \n  select(obese_DXA, obese_BMI, obese_WC, Age_recode, Sex, Race)\n\n# Stack for IPD\ncombined2 <- bind_rows(\n  labeled2   |> mutate(set_label = \"labeled\"),\n  unlabeled2 |> mutate(set_label = \"unlabeled\")\n)\n```\n:::\n\n\n\n\n\nNow let us rerun `ipd::ipd()` and compare our results to the **Naive** and \n**Classical** models:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Note: This code chunk now runs without error!\nipd_bmi_fit <- ipd(\n    formula = obese_DXA - obese_BMI ~ Age_recode + Sex + Race,\n    method  = \"pspa\",\n    model   = \"logistic\",\n    data    = combined2,\n    label   = \"set_label\"\n)\n\nipd_wc_fit <- ipd(\n    formula = obese_DXA - obese_WC ~ Age_recode + Sex + Race,\n    method  = \"pspa\",\n    model   = \"logistic\",\n    data    = labeled2,\n    unlabeled_data = unlabeled2\n)\n\n# Collect results using the tidy() method\nipd_bmi_df <- tidy(ipd_bmi_fit) |>\n  mutate(method = \"IPD (BMI)\")\n\nipd_wc_df  <- tidy(ipd_wc_fit) |>\n  mutate(method = \"IPD (WC)\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Rerun previous models\n# Naive on unlabeled using BMI\nnaive_bmi_fit <- glm(obese_BMI ~ Age_recode + Sex + Race, \n  family = binomial, data = unlabeled2)\nnaive_bmi_df  <- broom::tidy(naive_bmi_fit) |>\n  mutate(method = \"Naive (BMI)\")\n\n# Naive on unlabeled using WC\nnaive_wc_fit <- glm(obese_WC ~ Age_recode + Sex + Race,\n  family = binomial, data = unlabeled2)\nnaive_wc_df  <- broom::tidy(naive_wc_fit) |>\n  mutate(method = \"Naive (WC)\")\n\n# Classical on labeled using DXA\nclass_fit <- glm(obese_DXA ~ Age_recode + Sex + Race,\n  family = binomial, data = labeled2)\nclass_df  <- broom::tidy(class_fit) |>\n  mutate(method = \"Classical (DXA)\")\n\n# Combine\ncoef_df <- bind_rows(\n  ipd_bmi_df, ipd_wc_df, naive_bmi_df, naive_wc_df, class_df) |>\n  filter(term != \"(Intercept)\") |>\n  mutate(\n    term = recode(term,\n      \"Age_recode20-39\" = \"Age 20-39 (vs Under 20)\",\n      \"Age_recode40+\" = \"Age 40+ (vs Under 20)\",\n      \"SexFemale\" = \"Female (vs Male)\",\n      \"RaceNon-Hispanic Black\" = \"Non-Hispanic Black (vs Non-Hispanic White)\",\n      \"RaceNon-Hispanic Asian\" = \"Non-Hispanic Asian (vs Non-Hispanic White)\",\n      \"RaceHispanic\" = \"Hispanic (vs Non-Hispanic White)\",\n      \"RaceOther Race - Including Multi-Racial\" = \"Other Race - Including Multi-Racial (vs Non-Hispanic White)\"\n    ),\n    method = factor(method, \n      levels = c(\"IPD (BMI)\", \"IPD (WC)\", \n                 \"Classical (DXA)\", \"Naive (BMI)\", \"Naive (WC)\"))\n  )\n    \n# Forest plot\nggplot(coef_df, aes(x = estimate, y = term, \n    color = method, fill = method, shape = method)) +\n  geom_point(position = position_dodge(width = 0.6)) +\n  geom_errorbarh(aes(xmin = estimate - 1.96 * std.error,\n                     xmax = estimate + 1.96 * std.error),\n                 height = 0.2,\n                 position = position_dodge(width = 0.6)) +\n  geom_vline(xintercept = 0, linetype = \"dashed\") +\n  scale_y_discrete(limits = rev) +\n  scale_fill_manual(\n    values = c(\n      \"Classical (DXA)\" = \"#1B365D\", \n      \"Naive (BMI)\"     = \"#00C1D5\", \n      \"Naive (WC)\"      = \"#AA4AC4\",\n      \"IPD (BMI)\"       = \"#00C1D5\",\n      \"IPD (WC)\"        = \"#AA4AC4\"\n    )\n  ) +\n  scale_color_manual(\n    values = c(\n      \"Classical (DXA)\" = \"#1B365D\", \n      \"Naive (BMI)\"     = \"#00C1D5\", \n      \"Naive (WC)\"      = \"#AA4AC4\",\n      \"IPD (BMI)\"       = \"#00C1D5\",\n      \"IPD (WC)\"        = \"#AA4AC4\"\n    )\n  ) +\n  scale_shape_manual(\n    values = c(\n      \"Classical (DXA)\" = 16, \n      \"Naive (BMI)\"     = 16, \n      \"Naive (WC)\"      = 16,\n      \"IPD (BMI)\"       = 17,\n      \"IPD (WC)\"        = 17\n    )\n  ) +\n  labs(\n    x = \"Log-Odds Estimate (95% CI)\",\n    y = \"Covariate\",\n    title = \"Comparison of Obesity Model Coefficients\",\n    color = \"Model Type\", fill = \"Model Type\", shape = \"Model Type\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`height` was translated to `width`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Unit02_MeasuringAdiposity_files/figure-html/unnamed-chunk-20-1.png){width=100%}\n:::\n:::\n\n\n\n\n\n>\n> **Key Point:** The IPD methods combine both cohorts, using the labeled DXA values and the proxy in the unlabeled cohort to correct bias and recover valid estimates for the effect of Age, Sex, and Race/Ethnicity on true adiposity.\n>\n\n## Summary and Key Takeaways\n\n- **BMI** and **WC** are imperfect proxies for DXA-based % body fat. \n- **Naive** regression on BMI or WC leads to biased estimates for associations between obesity and risk factors such as age, sex, and race.\n- **Classical** regression on true DXA-based % fat is unbiased but costly.\n- **IPD** allows you to leverage a *large cohort with only BMI + covariates*, correct for prediction error, and recover unbiased estimates with more precision than the **Classical** approach.\n- Understanding how different *proxies* like BMI and WC affect **population-level inference** is important for epidemiologic and clinical studies.\n\n## References\n\n* Visokay, Adam, et al. \"How to measure obesity in public health research? Problems with using BMI for population inference.\" *medRxiv* (2025): 2025-04.\n\n---\n\n*This is the end of the module. We hope this was informative! For question/concerns/suggestions, please reach out to ssalerno@fredhutch.org*\n",
    "supporting": [
      "Unit02_MeasuringAdiposity_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}